### PR TITLE
Added a sanitized_input function

### PR DESCRIPTION
**Pull request by Dogeek**
- no eval is used
- casts into whatever object
- docstring
- set number of retries (<0 for infinite)
- custom message
- custom error message
- valid inputs in any iterable check

### CODE REVIEW

**Comment by cdgriffith** [comment]
Hello @Dogeek  thanks for the PR! 

If you could, please add the [asked for tests ](https://github.com/cdgriffith/Reusables/blob/master/CONTRIBUTING.rst) to give your code proper coverage. 

>
> - New features should have
>    - Reasoning for addition in pull request
>    - Docstring with code block example and parameters
>    - Tests with as much coverage as reasonable
>    - Tests should go through both sad and happy paths

**Comment by Dogeek** [comment]
oh I see, I'll update my code to not use f-strings (it's one of those things you don't think about)

**Comment by Dogeek** [comment]
As for a case for this function, I wrote it in response to a question on the r/learnpython subreddit, I thought it was quite nicely written, with plenty of features, and since it's a commonly needed thing, I thought I'd make my case for it to be added to the reusables package.

**Comment by Dogeek** [comment]
please let me know if there is anything else you need me to do before the PR can be accepted (I would think in the develop branch). So far, I've written tests for everything I think should be possible with the function. If I figure out a way to reliably read sys.stdout without interfering with its behavior, I can think of a few more tests to execute.

I also thought of adding the 'chain cast' feature, but I do not know how relevant that would be, given that the only real application would be to enable casts like "2.3" directly to int. It's really not hard to implement though, so I might as well do it.

**Comment by cdgriffith** [comment]
Thanks for all your hard work on this, I think it is good to go! I am going to figure out what's up with these tests and hope to have release out either this week or weekend (feel free to bug me if I don't).

**Comment by cdgriffith** [comment]
@Dogeek in PR for master now with some modifications https://github.com/cdgriffith/Reusables/pull/52/files#diff-b059323babd4418cda5a944f5be030feR21

I spelled everything out a bit more, changed docs to match others, and other small changes but should work identically to before. And of course added you to authors file. Thanks for the great contribution!

 If you disagree with any of the changes let me know, just trying to make it match current repo styling. Feel free to give it a review!

**Comment by Dogeek** [comment]
A few notes :

- given that you're defining a function (_get_input), to ensure compatibility with python 2, raw_input should be returned instead of input.

- you renamed cast_obj to cast_as which is fine but you should also update the docstring to reflect this change (I saw cast_obj a few times in there)

- I'll check the unittest docs to see if there is a way to assert that a specific string is sent to stdout, would be nice to write tests for that.

**Comment by cdgriffith** [comment]
good call with the get input to raw input, I only did it to mock the input earier in the tests lol

**Pull request merged**
